name: OCamlformat

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 5

      - name: Install OCamlformat
        run: |
          opam install ocamlformat

      - name: OCamlformat
        run: |
          eval $(opam env)
          # shopt -s globstar # allows **/*.ml to search nested subdirectories
          find . -name "*.ml" -not -path "./_opam/*"
          ocamlformat --check $(find . -name "*.ml" -not -path "./_opam/*")
