name: Dune Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LLVM 
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "14"
     
      - name: Setup OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4

      - name: Install deps
        run: |
          opam install . --deps-only --yes

      - name: Run tests
        run: |
          eval $(opam env) # adds dune to path
          dune runtest
